### ISSUE TITLE
detected face 0

### ISSUE THREAD

**Issue by mmaithani** [sthanhng/yoloface#18]
\

**Comment by 1Hussnain1** [comment]
facing the same issue

**Comment by OgeNI** [comment]
I also run this project and the number of faces detected are 0. 
Reads:
yoloface % python yoloface.py --image samples/outside_000001.jpg --output-dir outputs/
----- info -----
('[i] The config file: ', './cfg/yolov3-face.cfg')
('[i] The weights of model file: ', './model-weights/yolov3-wider_16000.weights')
('[i] Path to image file: ', 'samples/outside_000001.jpg')
('[i] Path to video file: ', '')
###########################################################

==> Skipping create the outputs/ directory...
[i] ==> # detected faces: 0
############################################################
[i] ==> Done processing!!!
('[i] ==> Output file is stored at', 'outputs/outside_000001_yoloface.jpg')
==> All done!
***********************************************************

**Comment by OgeNI** [comment]
The same result goes for any face I try detecting - faces detected - 0. Please are we using the correct weights? Thank you.

**Comment by mmaithani** [comment]
closing issue
