### ISSUE TITLE
OPENCV Failed to parse NetParameter file

### ISSUE THREAD

**Issue by 448357739** [sthanhng/yoloface#21]
Hi,I just use OPENCV in python to detect face. I use current weigh in the link and yolo cfg in cfg folder.
I use  'cv.dnn.readNetFromDarknet(modelConfiguration, modelWeights)' 
and get this error 'Failed to parse NetParameter file: yolov3-wider_16000.weigh in function 'cv::dnn::dnn4_v20191202::readNetFromDarknet'' 
Anyone can give me some advice?

**Comment by 448357739** [comment]
problem solved

**Comment by RajaParikshit** [comment]
How ???

**Comment by choisaywhy** [comment]
how??

**Comment by choisaywhy** [comment]
i solved it by adding this file to model-weights folder
https://pjreddie.com/media/files/yolov3.weights
