### ISSUE TITLE
where to get the "YOLO_Face.h5" file in yoloface_gpu.py

### ISSUE THREAD

**Issue by NUAAXQ** [sthanhng/yoloface#3]
I want to run the yoloface_gpu.py, but I did not find the "YOLO_Face.h5".

**Comment by sthanhng** [comment]
> I want to run the yoloface_gpu.py, but I did not find the "YOLO_Face.h5".

@NUAAXQ 

I have updated the script to download the "YOLO_Face.h5" model. You can find and download it [here](https://github.com/sthanhng/yoloface/issues/3#issue-377710366).

Thank you!

**Comment by Ohad-Multisense** [comment]
> > I want to run the yoloface_gpu.py, but I did not find the "YOLO_Face.h5".
> 
> @NUAAXQ
> 
> I have updated the script to download the "YOLO_Face.h5" model. You can find and download it [here](https://github.com/sthanhng/yoloface/blob/master/model-weights/get_YOLO_Face_h5.sh).
> 
> Thank you!

hello, i try to download YOLO_Face.h5 but it wrote that file not exist, can you please re upload? 
thanks
